### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by simonhir** [die-wegmeister/Wegmeister.SendInBlue#1]
Hi @Benjamin-K,

since I am currently looking for a package like this but no license is defined I wanted to ask if there are any restrictions. 
Furthermore I would like to add the possibility to deactivate DOI and of course make this change available as PR again (If wanted).

Best regards
Simon

**Comment by Benjamin-K** [comment]
Hi @simonhir, sorry for the late reply. The package uses MIT license. I will update this soon. We will possibly also add support for Fusion forms in the near future. 
Feel free to create a PR for registrations without DOI. But keep in mind, that this normally is required in most cases when you plan to send newsletters to the given email addresses.
